package minicraft.screen;

import minicraft.core.FileHandler;
import minicraft.core.Game;
import minicraft.core.Renderer;
import minicraft.core.io.InputHandler;
import minicraft.core.io.Settings;
import minicraft.entity.Direction;
import minicraft.entity.mob.Player;
import minicraft.gfx.*;
import minicraft.gfx.Color;
import minicraft.gfx.Font;
import org.apache.commons.io.monitor.FileEntry;
import org.apache.xmlgraphics.image.loader.ImageSource;
import org.apache.xmlgraphics.image.loader.impl.ImageLoaderPNG;

import javax.imageio.ImageIO;
import javax.imageio.stream.FileImageInputStream;
import javax.imageio.stream.ImageInputStream;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

public class SkinDisplay extends Display {

	public static final String DEFAULT_SKIN = "Paul"; // Default Skin :)
    public static final String CAPE_SKIN = "Paul (Cape)"; // Built-in Skin :)
    public static final String FAMILIARBOY_SKIN = "Familiar Boy"; // Built-in Skin :)
    public static final String FAMILIARGIRL_SKIN = "Familiar Girl"; // Built-in Skin :)
    public static final String CUSTOM_SKIN = "Custom"; // User's Custom Imported Skin :)

	private static final String[] ENTRY_NAMES = new String[] { "skins.png" }; // Spritesheets

	public final List<String> textureList;
	public final List<String> textureIDList;
	private final File location;

	private int selected;
	public static String SkinOutput = SkinDisplay.DEFAULT_SKIN;

	private boolean shouldUpdate;
	private Screen lastScreen;

	public static MobSprite[][] CustomSkinsprites = MobSprite.compilePlayerSpriteAnimations(0, 0);
	public static MobSprite[][] CustomSkincarrySprites = MobSprite.compilePlayerSpriteAnimations(0, 2); // the sprites while carrying something.
	public static MobSprite[][] CustomSkinsuitSprites = MobSprite.compilePlayerSpriteAnimations(8, 0); // the "airwizard suit" sprites.
	public static MobSprite[][] CustomSkincarrySuitSprites = MobSprite.compilePlayerSpriteAnimations(8, 2); // the "airwizard suit" sprites.

	/* The skins are put in a folder generated by the game called "Skins".
	 * Many skins can be put according to the number of files.
	 */

	public SkinDisplay() {
		this.textureList = new ArrayList<>();
		this.textureIDList = new ArrayList<>();
		this.textureList.add(SkinDisplay.DEFAULT_SKIN);
		this.textureList.add(SkinDisplay.CAPE_SKIN);
		this.textureList.add(SkinDisplay.FAMILIARBOY_SKIN);
		this.textureList.add(SkinDisplay.FAMILIARGIRL_SKIN);
		this.textureIDList.add(SkinDisplay.DEFAULT_SKIN);
		this.textureIDList.add(SkinDisplay.CAPE_SKIN);
		this.textureIDList.add(SkinDisplay.FAMILIARBOY_SKIN);
		this.textureIDList.add(SkinDisplay.FAMILIARGIRL_SKIN);
		this.textureIDList.add(SkinDisplay.CUSTOM_SKIN);

		// Generate skins folder and/or read it.
		this.location = new File(FileHandler.getSystemGameDir() + "/" + FileHandler.getLocalGameDir() + "/Skins");
		this.location.mkdirs();

		// Read and add the .png file to the skins list
		for (String fileName : Objects.requireNonNull(location.list())) {
			if (fileName.endsWith(".png")) { // only .png skins files ok?
				textureList.add(fileName);
			}
		}

		selected = Settings.getIdx("Skins");
	}

	public void updateSpriteSheet(Screen screen) throws IOException {
		SpriteSheet[] sheets = new SpriteSheet[1];

		sheets[0] = new SpriteSheet(ImageIO.read(Game.class.getResourceAsStream("/resources/textures/skins.png")));

		if (selected == 0) {
			SkinOutput = textureIDList.get(0);
		}
		else if (selected == 1) {
			SkinOutput = textureIDList.get(1);
		}
		else if (selected == 2) {
			SkinOutput = textureIDList.get(2);
		}
		else if (selected == 3) {
			SkinOutput = textureIDList.get(3);
		}
		else if (selected > 3) {
			SkinOutput = textureIDList.get(4);
			File imageLocation = new File(location, textureList.get(selected));
			sheets[0] = new SpriteSheet(ImageIO.read(imageLocation));
		}
		screen.setSkinSheet(sheets[0]);
	}

    @Override
    public void onExit() {
        Settings.getEntry("Skins").setSelection(selected);
        try {
            updateSpriteSheet(lastScreen);
        } catch (IOException exception) {
            exception.printStackTrace();
        }
	new Save();
        Game.exitMenu();
    }

	@Override
	public void tick(InputHandler input) {
		if (input.getKey("menu").clicked || input.getKey("attack").clicked || input.getKey("exit").clicked) {
			Game.exitMenu();
			return;
		}
		if (input.getKey("cursor-down").clicked && selected > 0) {
			selected--;

		}
		if (input.getKey("cursor-up").clicked && selected < textureList.size() - 1) {
			selected++;
		}
	}

	// In case the name is too big ...
	private static String shortNameIfLong(String name) {
		return name.length() > 22 ? name.substring(0, 16) + "..." : name;
	}

	@Override
	public void render(Screen screen) {
		screen.clear(0);

		lastScreen = screen;

		String selectedUp = selected + 1 > textureList.size() - 1 ? "" : textureList.get(selected + 1);
		String selectedDown = selected - 1 < 0 ? "" : textureList.get(selected - 1);

		// Render the menu
		Font.drawCentered("Skins", screen, Screen.h - 180, Color.YELLOW); // Title
		Font.drawCentered(SkinDisplay.shortNameIfLong(selectedDown), screen, Screen.h - 70, Color.GRAY); // Unselected space
		Font.drawCentered(SkinDisplay.shortNameIfLong(textureList.get(selected)), screen, Screen.h - 80, Color.GREEN); // Selection
		Font.drawCentered(SkinDisplay.shortNameIfLong(selectedUp), screen, Screen.h - 90, Color.GRAY); // Other unselected space
		Font.drawCentered("Use "+ Game.input.getMapping("cursor-down") + ", " + Game.input.getMapping("cursor-up") + ", " + Game.input.getMapping("SELECT"), screen, Screen.h - 11, Color.get(0, 222, 222, 222)); // Controls

		int h = 2;
		int w = 15;
		int xo = (Screen.w - w * 8) / 2;
		int yo = 28;


		for (int y = 0; y < h; y++) {
			for (int x = 0; x < w; x++) {
				screen.render(xo + x * 8, yo + y * 8, x + y * 32, 0, 3); // Texture pack logo
			}
		}

		/* Unnecessary for now...
	     * This part is used to test the change of textures
	     * in some future it may be useful
	     *
	     *screen.render(24, 48, 134, Color.get(-1, 110, 330, 550), 0);
	     *screen.render(48, 48, 136, Color.get(-1, 110, 330, 550), 0);
	     *screen.render(72, 48, 164, Color.get(-1, 100, 321, 45), 0);
	     *screen.render(96, 48, 384, Color.get(0, 200, 500, 533), 0);
	     *screen.render(120, 48, 135, Color.get(-1, 100, 320, 430), 0);
	     */
	}

}
